export const types ={
    GET_MOVIES: 'GET_MOVIES',
    GET_FAVORITES: 'GET_FAVORITES',
    SEARCH_FAVORITES: 'SEARCH_FAVORITES',
    CHANGE_OBS: 'CHANGE_OBS',
    CHANGE_FAVORITES: 'CHANGE_FAVORITES',
    ATT_LIST: 'ATT_LIST'
}