export const types ={
    GET_MOVIES: 'GET_MOVIES',
    GET_FAVORITES: 'GET_FAVORITES',
    SEARCH_FAVORITES: 'SEARCH_FAVORITES',
    CLEAR_FAVORITES: 'CLEAR_FAVORITES',
    CHANGE_OBS: 'CHANGE_OBS'
}